#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source colors
if [[ -s "${ZDOTDIR:-$HOME}/.dotfiles/resources/base16-shell/scripts/base16-tomorrow-night.sh" ]]; then
    source "${ZDOTDIR:-$HOME}/.dotfiles/resources/base16-shell/scripts/base16-tomorrow-night.sh"
fi

